#ifndef __H_GMBSOCK_L_BROMPACKET
#define __H_GMBSOCK_L_BROMPACKET

#include "../Defines.h"
#include "../Gmod_Headers/Lua/Interface.h"

namespace GMBSOCK {
	GMOD_FUNCTION(CreatePacket);

	GMOD_FUNCTION(PACK__TOSTRING);
	GMOD_FUNCTION(PACK__EQ);
	GMOD_FUNCTION(PACK__GC);

	GMOD_FUNCTION(PACK_InSize);
	GMOD_FUNCTION(PACK_InPos);
	GMOD_FUNCTION(PACK_OutSize);
	GMOD_FUNCTION(PACK_OutPos);
	GMOD_FUNCTION(PACK_Clear);
	GMOD_FUNCTION(PACK_Copy);
	GMOD_FUNCTION(PACK_SetEndian);
	GMOD_FUNCTION(PACK_IsValid);

	GMOD_FUNCTION(PACK_WRITEByte);
	GMOD_FUNCTION(PACK_WRITESByte);
	GMOD_FUNCTION(PACK_WRITEShort);
	GMOD_FUNCTION(PACK_WRITEUShort);
	GMOD_FUNCTION(PACK_WRITEFloat);
	GMOD_FUNCTION(PACK_WRITEInt);
	GMOD_FUNCTION(PACK_WRITEUInt);
	GMOD_FUNCTION(PACK_WRITEDouble);
	GMOD_FUNCTION(PACK_WRITELong);
	GMOD_FUNCTION(PACK_WRITEULong);
	GMOD_FUNCTION(PACK_WRITEString);
	GMOD_FUNCTION(PACK_WRITEStringNT);
	GMOD_FUNCTION(PACK_WRITELine);
	GMOD_FUNCTION(PACK_WRITEPacket);
	GMOD_FUNCTION(PACK_WRITEStringRaw);

	GMOD_FUNCTION(PACK_READByte);
	GMOD_FUNCTION(PACK_READSByte);
	GMOD_FUNCTION(PACK_READShort);
	GMOD_FUNCTION(PACK_READUShort);
	GMOD_FUNCTION(PACK_READFloat);
	GMOD_FUNCTION(PACK_READInt);
	GMOD_FUNCTION(PACK_READUInt);
	GMOD_FUNCTION(PACK_READDouble);
	GMOD_FUNCTION(PACK_READLong);
	GMOD_FUNCTION(PACK_READULong);
	GMOD_FUNCTION(PACK_READStringNT);
	GMOD_FUNCTION(PACK_READStringAll);
	GMOD_FUNCTION(PACK_READLine);
	GMOD_FUNCTION(PACK_READUntil);
	GMOD_FUNCTION(PACK_READString);
}

#endif